inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'work/**/*'
  NewCops: enable
  SuggestExtensions: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
